---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  require_ansible_repo: true
  ansible_verbose: true
  playbook: tests/testkitchen.yml
  hosts: localhost
  extra_vars:
    threatstack_deploy_key: <%= ENV['TS_DEPLOY_KEY'] != nil ? ENV['TS_DEPLOY_KEY'] : 'ts_deploy_key' %>
    <% if ENV['TS_NO_CONFIG_AGENT']  %>
    threatstack_configure_agent: false
    <% end %>
    threatstack_agent_config_args: <%= ENV['TS_CONFIG_ARGS'] %>
    <% if ENV['TS_PACKAGE_VERSION'] %>
    # Should be in form threatstack-version=<version>.  ex. threatstack-version=1.4.4.0ubuntu14.0
    threatstack_pkg: <%= ENV['TS_PACKAGE_VERSION'] %>
    <% end %>
    <% if ENV['TS_RULE_SETS'] %>
    threatstack_ruleset: "<%= ENV['TS_RULE_SETS'] %>"
    <% end %>
    <% if ENV['TS_HOSTNAME'] %>
    threatstack_hostname: "<%= ENV['TS_HOSTNAME'] %>"
    <% end %>
    <% if ENV['TS_URL'] %>
    threatstack_url: "<%= ENV['TS_URL'] %>"
    <% end %>

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.8
  - name: debian-8.1
  - name: fedora-25
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
