---
- name: Check auditd status
  command: service auditd status
  register: auditd_status
  ignore_errors: true
  changed_when: false

- name: Stop service auditd
  command: service auditd stop
  when: auditd_status.rc == 0
  ignore_errors: "{{ ansible_check_mode }}"

- name: Disable service auditd
  command: systemctl disable auditd
  when: auditd_status.rc == 0
  ignore_errors: "{{ ansible_check_mode }}"
