---
# Setup tasks
- name: Run Apt configure and install Threat Stack
  include: apt_install.yml
  when: ansible_os_family == 'Debian'

- name: Run Yum Configure and install Threat Stack
  include: yum_install.yml
  when: ansible_os_family == 'RedHat'

- name: Fire cloudsight setup
  include: cloudsight_setup.yml
  when: threatstack_configure_agent == true
