---
- name: Define some facts based on variables
  include: facts.yml

- name: Ensure package URL is defined
  include: pkg_url.yml
  when: threatstack_pkg_url is undefined

- name: Disable auditd service
  include: disable_auditd.yml
  when:
    - ansible_os_family == 'RedHat'
    - (ansible_distribution != 'Amazon' or ansible_kernel is search("\.amzn2\."))

- name: Run Apt configure and install Threat Stack
  include: apt_install.yml
  when: ansible_os_family == 'Debian'

- name: Run Yum Configure and install Threat Stack
  include: yum_install.yml
  when: ansible_os_family == 'RedHat'

- name: 1.x agent setup
  include: cloudsight_setup.yml
  when:
    - threatstack_configure_agent == true
    - threatstack_v1

- name: 2.x agent setup
  include: tsagent_setup.yml
  when:
    - threatstack_configure_agent == true
    - not threatstack_v1
